### ISSUE TITLE
Realidad virtual

### ISSUE THREAD

**Issue by vicfic** [vicfic/SmartHouse#4]
- Crear una rama que se llame "realidad-aumentada"
- Definir una primera aproximación, que consiste el detectar un marcador concreto con realidad aumentada.

Tras haberlo hablado en clase, entendemos que para esta primera aproximación no se necesita que haya más cosas implementadas en nuestra aplicación.

**Comment by drivasudc** [comment]
Como contiene varias subtareas, se transforma en una Epic para contener y ver el progreso de cada parte por separado
